name: Run Python Selenium headless script to automate free daily tokens collection on dreampress.ai

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: "0 10 * * *" # every day at 10:00 AM

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install Python
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x #install the python needed

      - name: execute py script # run the run.py to get the latest data
        run: |
          pip install --upgrade pip
          pip install selenium

      - name: Install Microsoft Edge Driver
        run: |
          sudo apt-get install -y wget unzip software-properties-common
          # Add Microsoft Edge repository
          curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list'
          sudo rm microsoft.gpg
          sudo apt-get update
          # Install Microsoft Edge
          sudo apt-get install -y microsoft-edge-dev
          # Install Edge WebDriver
          EDGE_VERSION=$(microsoft-edge --version | grep -oP '(\d+\.\d+\.\d+\.\d+)')
          wget https://msedgedriver.azureedge.net/$EDGE_VERSION/edgedriver_linux64.zip
          unzip edgedriver_linux64.zip
          sudo mv msedgedriver /usr/local/bin/
          rm edgedriver_linux64.zip

      - name: Raise the resume
        run: python ./bot/collect-tokens.py
        env:
          LOGIN: ${{ secrets.LOGIN }}
          KEY: ${{ secrets.KEY }} # if run.py requires passwords..etc, set it as secrets
