name: Run Python Selenium headless script to automate free daily tokens collection on dreampress.ai

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: "0 5 * * *" # Runs at 05:00 UTC every day
    # - cron: "0 * * * *" # this line is for testing purposes, runs the script every hour

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install Python
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x # install the python needed

      - name: install dependencies
        run: |
          pip install --upgrade pip
          pip install -U selenium webdriver-manager

      - name: execute Your python script to collect the tokens
        run: python ./bot/collect-tokens.py
        env:
          LOGIN: ${{ secrets.LOGIN }}
          KEY: ${{ secrets.KEY }} # set your login and password to dreampress.ai in the repo secrets before running the script

      - name: Take screenshot on failure
        if: failure() # This ensures the step only runs if the previous steps failed
        run: |
          mkdir -p ./screenshots
          mv error.png ./screenshots
        # Add this to the end of your job
      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        if: always() # This ensures the artifacts are always uploaded, even if the workflow fails
        with:
          name: screenshots
          path: ./screenshots/
